name: Sync Files from JSON

on:
  push:
    branches:
      - files
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: files

      - name: Create temporary folder
        run: mkdir -p /tmp/files

      - name: Copy files.json to temporary folder
        run: cp files.json /tmp/files/files.json

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main  # 切换到 main 分支

      - name: Read files.json and download files
        run: |
          #!/bin/bash
          set -e
          # 读取 files.json 文件
          cat /tmp/files/files.json | jq -r '.[] | " $.filename)  $.download_url)"' | while read -r line; do
            filename=$(echo "$line" | awk '{print $1}')
            download_url=$(echo "$line" | awk '{print $2}')
            echo "Processing file: $filename"

            # 检查文件是否已存在
            if [ -f "files/$filename" ]; then
              echo "Removing existing file: $filename"
              rm -f "files/$filename"
            fi

            # 下载文件
            echo "Downloading file: $filename"
            curl -L -o "files/$filename" "$download_url"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add files/
          git commit -m "Update files" || true
          git push origin main

      - name: Checkout status branch
        uses: actions/checkout@v4
        with:
          ref: status  # 切换到 status 分支

      - name: Update status file
        run: |
          awk '{print $1+1}' number.txt > temp.txt && mv temp.txt number.txt

      - name: Commit and push changes to status branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add status
          git commit -m "Update status" || true
          git push origin status
