name: Download Files and Deploy Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  download-files-and-update-status:
    runs-on: ubuntu-latest

    steps:
      # 检出 main 分支
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      # 读取 files.json 文件并下载文件
      - name: Read and download files from files.json
        run: |
          curl -L -o "files/ollama.sh" "https://raw.githubusercontent.com/CMSZ001/Ollama_for_Termux/refs/heads/main/install.sh"

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: files

      # 提交并推送下载的文件到 main 分支
      - name: Commit and push files to main branch
        run: |
          # 配置Git用户信息
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            echo "Changes detected. Committing files..."
            git add files/
            git commit -m "Download files"
            git push --force-with-lease origin mai
          fi
